version: '3'

services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    working_dir: /var/www
    volumes:
      - ./:/var/www
  
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    ports:
    - "3310:3306"
    volumes:
    - ./mysql/dbdata:/var/lib/mysql
    environment:
    - MYSQL_DATABASE=workshop
    - MYSQL_ROOT_PASSWORD=root